import { VercelRequest, VercelResponse } from '@vercel/node';
import ytdl from 'ytdl-core';

export default async (req: VercelRequest, res: VercelResponse) => {
  const songUrl: string = req.query.url as string;

  try {
    const songInfo = await ytdl.getInfo(songUrl);
    const songDescription = songInfo.videoDetails.description;
    const songTitle = songInfo.videoDetails.title;
    const audioFormats = ytdl.filterFormats(songInfo.formats, 'audioonly');

    res.status(200).json({
      audioURL: audioFormats[0].url,
      audioFormat: audioFormats[0].mimeType,
      description:
        songDescription && removeMetadata(songDescription, songTitle),
      songTitle,
    });
  } catch (error) {
    res.status(500).json({ error: 'Error fetching audio formats' });
  }
};

const removeMetadata = (text: string, songTitle: string): string => {
  // Find the index of the video title in the text
  const titleIndex = text.indexOf(songTitle);

  // If the title is found, remove the title and the two characters immediately following it
  if (titleIndex !== -1) {
    text = text.substring(titleIndex + songTitle.length + 2); // Adding 2 for the two characters following the title
  }

  // Define patterns to remove
  const patterns: RegExp[] = [
    /℗ Nippon Columbia Co\., Ltd\.\/NIPPONOPHONE/,
    /Released on: \d{4}-\d{2}-\d{2}/,
    /Auto-generated by YouTube\./,
  ];

  // Iterate over patterns and remove them from the text
  patterns.forEach((pattern) => {
    text = text.replace(pattern, '');
  });

  // Remove the video title
  text = text.replace(songTitle, '');

  // Remove extra spaces and return the cleaned text
  return text.trim().replace(/\s+/g, ' ');
};
